version: "3.4"

services:
  blog-api:
    image: blog-api:latest
    container_name: blog-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 5150:80
    depends_on:
      blog.db:
        condition: service_healthy

  blog.db:
    image: postgres:latest
    container_name: blog-database
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/postgres:/var/lib/postgresql/data
    ports:
      - 5151:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 25
